//
// Created by Jamie on 23/12/2017.
//

#ifndef BLACKJACK_CARDCOUNT_CARDCOUNTBLACKJACK_H
#define BLACKJACK_CARDCOUNT_CARDCOUNTBLACKJACK_H

void cardCountBlackJack();

#endif //BLACKJACK_CARDCOUNT_CARDCOUNTBLACKJACK_H
